#extension GL_ARB_compute_shader : enable
#extension GL_ARB_shader_storage_buffer_object : enable

layout(std140) buffer Pos
{
	vec4 Positions[];
};

layout(std140) buffer Vel
{
	vec4 Velocities[];
};

uniform uint ParticleCount;

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
	uint gid = gl_GlobalInvocationID.x;

	if (gid > ParticleCount)
	{
		return;
	}

	vec3 pos = Positions[gid].xyz;

	pos.y += 0.06f;

	Positions[gid].xyz = pos;
}