name: CMake Build

on: [push]

jobs:
  linux_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: sudo apt update && sudo apt-get install xorg-dev libglu1-mesa-dev

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory.
        # We'll use this as our working directory for all subsequent commands.
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable access regardless of the host operating system.
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source and build directories,
        # but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: |
          cmake "$GITHUB_WORKSPACE" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=gcc-10 \
            -DBUILD_TESTING=OFF \
            -DNEWTON_BUILD_SANDBOX_DEMOS=OFF \
            -DCMAKE_CXX_COMPILER=g++-10 \
            -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF \
            -DASSIMP_BUILD_FBX_IMPORTER=ON \
            -DASSIMP_BUILD_DRACO=OFF \
            -DASSIMP_NO_EXPORT=ON

      - name: Build Engine
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute the build.
        # You can specify a specific target with "--target <NAME>".
        run: cmake --build . --config Release --target BaseApp

  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory.
        # We'll use this as our working directory for all subsequent commands.
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: pwsh
        working-directory: ${{runner.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source and build directories,
        # but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: |
          cmake "${env:GITHUB_WORKSPACE}" `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_TESTING=OFF `
            -DNEWTON_BUILD_SANDBOX_DEMOS=OFF `
            -DCMAKE_C_COMPILER=gcc-10 `
            -DCMAKE_CXX_COMPILER=g++-10 `
            -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF `
            -DASSIMP_BUILD_FBX_IMPORTER=ON `
            -DASSIMP_BUILD_DRACO=OFF `
            -DASSIMP_NO_EXPORT=ON `
            -G "Visual Studio 16 2019" -A x64

      - name: Build Engine
        working-directory: ${{runner.workspace}}/build
        shell: pwsh
        # Execute the build.
        # You can specify a specific target with "--target <NAME>".
        run: cmake --build . --config Release --target BaseApp
